"""Sample filings for demonstrating the dashboard.

Fictional issuers, deliberately. Real tickers with model-generated ratings would
read as genuine research on real companies the moment anyone screenshots it. The
filings themselves mirror the shape and language of real BSE/NSE disclosures so
the demo shows what the format actually looks like in use.
"""

from __future__ import annotations

from typing import Any

SAMPLE_SIGNALS: list[dict[str, Any]] = [
    {
        "uid": "sample:1",
        "symbol": "HELIOSCEM",
        "source": "BSE",
        "category": "Award of Order / Receipt of Order",
        "headline": (
            "Helios Cement Ltd - receipt of order worth INR 1,840 crore from NHAI "
            "for supply over 30 months"
        ),
        "direction": "BULLISH",
        "confidence": 0.88,
        "materiality": 5,
        "horizon_days": 20,
        "rationale": "Order is 34% of FY26 revenue with a defined 30-month execution window.",
        "key_risk": "Execution capacity is already committed through H1",
        "key_numbers": ["INR 1,840 cr", "34% of FY26 revenue", "30 months"],
        "filed_at": "2026-09-02T09:42:00+05:30",
    },
    {
        "uid": "sample:2",
        "symbol": "VARDHANPH",
        "source": "NSE",
        "category": "Regulation 30 Disclosure",
        "headline": (
            "Vardhan Pharma Ltd - resignation of Statutory Auditor citing "
            "unsatisfactory response to audit queries"
        ),
        "direction": "BEARISH",
        "confidence": 0.93,
        "materiality": 5,
        "horizon_days": 45,
        "rationale": "Auditor exit on unanswered queries; these situations deteriorate over weeks.",
        "key_risk": "Replacement auditor appointed quickly with a clean opinion",
        "key_numbers": [],
        "filed_at": "2026-09-02T10:15:00+05:30",
    },
    {
        "uid": "sample:3",
        "symbol": "MERIDSTL",
        "source": "BSE",
        "category": "Credit Rating",
        "headline": "Meridian Steel Ltd - CRISIL upgrades long-term rating to AA- from A+, outlook stable",
        "direction": "BULLISH",
        "confidence": 0.74,
        "materiality": 4,
        "horizon_days": 25,
        "rationale": "Upgrade cuts refinancing cost on INR 2,100 cr of debt maturing this year.",
        "key_risk": "Already anticipated after the Q1 deleveraging update",
        "key_numbers": ["AA- from A+", "INR 2,100 cr debt"],
        "filed_at": "2026-09-02T11:03:00+05:30",
    },
    {
        "uid": "sample:4",
        "symbol": "KAVERITEX",
        "source": "NSE",
        "category": "Regulation 30 Disclosure",
        "headline": "Kaveri Textiles Ltd - fire at Unit II, Coimbatore; operations suspended pending assessment",
        "direction": "BEARISH",
        "confidence": 0.81,
        "materiality": 4,
        "horizon_days": 30,
        "rationale": "Unit II is roughly 40% of spinning capacity; restart timeline not given.",
        "key_risk": "Insurance covers the loss and the restart is quick",
        "key_numbers": ["~40% of capacity"],
        "filed_at": "2026-09-02T12:20:00+05:30",
    },
    {
        "uid": "sample:5",
        "symbol": "ORIONLOG",
        "source": "BSE",
        "category": "Buyback",
        "headline": "Orion Logistics Ltd - Board approves buyback of up to INR 400 crore at INR 520 per share",
        "direction": "BULLISH",
        "confidence": 0.71,
        "materiality": 3,
        "horizon_days": 15,
        "rationale": "Buyback priced 14% above market; supports the floor while the tender runs.",
        "key_risk": "Small relative to float, so the support fades after the window",
        "key_numbers": ["INR 400 cr", "INR 520/share", "14% premium"],
        "filed_at": "2026-09-02T13:05:00+05:30",
    },
    {
        "uid": "sample:6",
        "symbol": "NILGIRIAG",
        "source": "NSE",
        "category": "Regulation 30 Disclosure",
        "headline": "Nilgiri Agro Ltd - GST department issues demand notice of INR 96 crore including penalty",
        "direction": "BEARISH",
        "confidence": 0.66,
        "materiality": 3,
        "horizon_days": 40,
        "rationale": "Demand is 11% of net worth; company says it will contest.",
        "key_risk": "Routinely reduced on appeal, as several peers have seen",
        "key_numbers": ["INR 96 cr", "11% of net worth"],
        "filed_at": "2026-09-02T13:48:00+05:30",
    },
    {
        "uid": "sample:7",
        "symbol": "SARASWATF",
        "source": "BSE",
        "category": "Board Meeting Intimation",
        "headline": "Saraswat Finserv Ltd - intimation of Board Meeting to consider fund raising via QIP",
        "direction": "BULLISH",
        "confidence": 0.52,
        "materiality": 2,
        "horizon_days": 12,
        "rationale": "Only an intimation to consider; size and pricing both unknown.",
        "key_risk": "A QIP at a discount is dilutive, not supportive",
        "key_numbers": [],
        "filed_at": "2026-09-02T14:10:00+05:30",
    },
    {
        "uid": "sample:8",
        "symbol": "HELIOSCEM",
        "source": "BSE",
        "category": "Newspaper Publication",
        "headline": "Helios Cement Ltd - newspaper publication of unaudited financial results for Q1 FY27",
        "direction": "NEUTRAL",
        "confidence": 0.95,
        "materiality": 0,
        "horizon_days": 0,
        "rationale": "Routine publication of results already disclosed.",
        "key_risk": "",
        "key_numbers": [],
        "filed_at": "2026-09-02T08:30:00+05:30",
    },
    {
        "uid": "sample:9",
        "symbol": "DECCANPWR",
        "source": "NSE",
        "category": "Compliance",
        "headline": "Deccan Power Ltd - closure of trading window for Q2 FY27 under the insider trading code",
        "direction": "NEUTRAL",
        "confidence": 0.97,
        "materiality": 0,
        "horizon_days": 0,
        "rationale": "Routine compliance filing with no economic content.",
        "key_risk": "",
        "key_numbers": [],
        "filed_at": "2026-09-02T08:05:00+05:30",
    },
    {
        "uid": "sample:10",
        "symbol": "ARAVALLIMIN",
        "source": "BSE",
        "category": "Regulation 30 Disclosure",
        "headline": "Aravalli Minerals Ltd - SEBI adjudication order imposing penalty of INR 12 crore on the company and promoters",
        "direction": "BEARISH",
        "confidence": 0.84,
        "materiality": 4,
        "horizon_days": 35,
        "rationale": "Penalty is small, but promoter involvement raises governance discount.",
        "key_risk": "Order is stayed on appeal to SAT",
        "key_numbers": ["INR 12 cr penalty"],
        "filed_at": "2026-09-02T15:02:00+05:30",
    },
]
